name: Ultimatevirus
version: ${project.version}
main: techwolfx.ultimatevirus.Ultimatevirus
api-version: 1.13
authors: [MasterWolfx]
description: Create a virus inside your server.
commands:
  mask:
    description: Get a mask to protect yourself from the virus.
  vaxin:
    description: Get a vaxin.
  virusreload:
    description: Reload the plugin.
  checkvirus:
    description: Check if you got the virus.