name: Ultimatevirus
version: ${project.version}
main: techwolfx.ultimatevirus.Ultimatevirus
api-version: '1.13'
authors: [MasterWolfx]
description: Add a fully customizable virus to your server.
softdepend: [PlaceholderAPI]
commands:
  virus:
    description: Display all the plugin commands.
    aliases: [ultimatevirus, uv, v]

permissions:
  ultimatevirus.bypass:
    description: Prevent virus infection
    default: op
  ultimatevirus.help:
    description: Allows the player to execute /virus help
  ultimatevirus.check:
    description: Allows the player to execute /virus check
  ultimatevirus.infectedlist:
    description: Allows the player to execute /virus infected
  ultimatevirus.checkothers:
    description: Allows the player to execute /virus check [player]
    default: op
  ultimatevirus.infect:
    description: Allows the player to execute /virus infect [player]
    default: op
  ultimatevirus.recover:
    description: Allows the player to execute /virus recover [player]
    default: op
  ultimatevirus.sethealth:
    description: Allows the player to execute /virus sethealth [player:*]
    default: op
  ultimatevirus.mask:
    description: Allows the player to execute /virus mask [player]
    default: op
  ultimatevirus.vaxin:
    description: Allows the player to execute /virus vaxin [player]
    default: op
  ultimatevirus.reload:
    description: Allows the player to execute /virus reload
    default: op