name: Ultimatevirus
version: ${project.version}
main: techwolfx.ultimatevirus.Ultimatevirus
authors: [MasterWolfx]
description: Add a virus in your server.
softdepend: [PlaceholderAPI]
commands:
  virus:
    description: Display all the plugin commands.
    aliases: [ultimatevirus, uv]